### ISSUE TITLE
Groovy example missing for Contract DSL

### ISSUE THREAD

**Issue by mlvandijk** [spring-cloud/spring-cloud.github.io#2]
The Groovy example for Contract DSL is missing (empty)

Steps to reproduce:
1. Go to: https://cloud.spring.io/spring-cloud-contract/spring-cloud-contract.html#contract-dsl
2. There is a box for Groovy, but no content for the example:
<img width="1397" alt="Screenshot 2019-07-01 at 11 21 53" src="https://user-images.githubusercontent.com/20927578/60425272-75aa5980-9bf2-11e9-866b-3d2ebd831105.png">

**Comment by spencergibb** [comment]
Please open in issue in spring-cloud-contract
